### ISSUE TITLE
What's up with the Victorian Web portion on Day 2?

### ISSUE THREAD

**Issue by dcnb** [uidaholib/cdil-summer2017#1]

**Comment by evanwill** [comment]
victorian web was a famous dh project before the internet and dh-- it's like an internet of digital victorian lit stuff, all self contained hyperlinked world. you would have a copy of it and navigate around. it's very interesting to see how they imagined a networked project without an internet to connect with.

**Comment by evanwill** [comment]
so, i thought it was an interesting conversation piece for platforms. creating an entire platform before there was the web. the idea of hyperlinking was incredibly fascinating to humanities in the 80s, there was these standalone desktop apps that let you write things sort of like a website is today--but it wasn't connected to the outside world. now we don't even think about hyperlinks--it's just normal. 

so i threw it in as an example of platforms before the internet, and how amazing it is that we have these options just a few decades later

**Comment by evanwill** [comment]
pre-web, [HyperCard](https://en.wikipedia.org/wiki/HyperCard) on mac desktops was like a local website viewer/editor/note keeping, and Brown Uni was creating [Intermedia](https://en.wikipedia.org/wiki/Intermedia_(hypertext)), as a pro-internet with surfing and editing, really a proto-wikipedia.

**Comment by dcnb** [comment]
That's interesting for sure. And I look forward to hearing you talk about it. I think we'll need to continually read the room though to determine at what level we might talk about these things, i.e. how technical they want to get.
